title: ""
author: Ignacio de Ramon
copyright: "© 2024 Whats Priced In"
logo: _static/logo.png 

# Book settings
html:  # the path to your logo image (relative to your book directory)
  favicon: _static/logo.png
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

# Execution settings
execute:
  execute_notebooks: force
  timeout: 600
  allow_errors: false

# Format settings
format:
  jb:
    execute:
      execute_notebooks: force 

repository:
  url: https://github.com/idram1984/idram1984.github.io
  branch: main  # or whatever your main branch is called